IMAGE_SIZE: [224, 224]

BATCH_SIZE: 32

EPOCHS: 15

LEARNING_RATE: 0.001

MODEL_NAME: ResNet50

INCLUDE_TOP: False

WEIGHTS: imagenet

CLASSES: 4

COLOR_MODE: rgb

NORMALIZE: True

TOP_K_SIMILAR_IMAGES: 5

model_inference:
  IMAGE_SIZE: [224, 224]
  CLASSES: 4
  CLASS_NAMES:
    - glioma
    - meningioma
    - no_tumor
    - pituitary