expected_num_classes: 4

DATA_VALIDATION:
  CLASSIFICATION_CLASSES:
    - glioma
    - meningioma
    - no_tumor
    - pituitary

allowed_formats:
  - JPEG

allowed_modes:
  - RGB
  - L

pixel_range:
  min: 0
  max: 255